### ISSUE TITLE
Android build errors with 0.22.1 around getLocales()

### ISSUE THREAD

**Issue by reedyrm** [rebeccahughes/react-native-device-info#459] opened 2018-07-27 13:07 UTC
## Summary

I recently just upped my version of this library to 0.22.1 from 0.21.5 and everything is working locally for me.  But when I run my build in Travis CI the build is failing with these errors.

Travis CI Java:
Switching to Oracle JDK8 (java-8-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-8-oracle

```
/home/travis/build/<user>/<appname>/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:71: error: cannot find symbol
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                                                    ^
  symbol:   variable N
  location: class VERSION_CODES
/home/travis/build/<user>/<appname>/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:72: error: cannot find symbol
      current = getReactApplicationContext().getResources().getConfiguration().getLocales().get(0);
                                                                              ^
  symbol:   method getLocales()
  location: class Configuration
/home/travis/build/<user>/<appname>/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:92: error: cannot find symbol
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                                                    ^
  symbol:   variable N
  location: class VERSION_CODES
/home/travis/build/<user>/<appname>/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:93: error: cannot find symbol
      current = getReactApplicationContext().getResources().getConfiguration().getLocales().get(0);
                                                                              ^
  symbol:   method getLocales()
  location: class Configuration
Note: /home/travis/build/<user>/<appname>/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
4 errors
:react-native-device-info:compileReleaseJavaWithJavac FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':react-native-device-info:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

|             |     |
| ----------- | --- |
| Version     | 0.22.1   |
| Affected OS | Android   |
| OS Version  | SDK 26  |

## Current behavior

Builds fails on gradle command

`/home/travis/build/<user>/<appname>/android/gradlew assembledevRelease -p ./android -DENVFILE=.env --no-daemon --max-workers 2`

## Expected behavior

Expecting the build to be successful.

**Comment by maksim-harakhovich-itechart** [comment] 2018-07-27 16:54
We do have the same issue.

**Comment by kingmatusevich** [comment] 2018-07-27 17:38
I have this issue locally.

**Comment by tbenr** [comment] 2018-07-27 18:06
same here.

**Comment by cusspvz** [comment] 2018-07-27 19:38
Same here

**Comment by cusspvz** [comment] 2018-07-27 19:43
Downgraded to `0.21.0` and it worked. Issue is only reproducible with `0.21.1`

**Comment by kingmatusevich** [comment] 2018-07-27 20:45
Downgrading to 0.21.5 worked for me.

**Comment by tbenr** [comment] 2018-07-27 20:46
0.21.5 ok for me too.

**Comment by machour** [comment] 2018-07-27 23:02
So sorry for that folks, this is related to #426 and will be dealt with it shortly

**Comment by ohtangza** [comment] 2018-07-27 23:10
Sorry folks. We are checking it now. Is there anyone who can share the `build.gradle` and java version?

**Comment by ohtangza** [comment] 2018-07-27 23:34
Oh, I guess I found the issue the `build.gradle` of this project (https://github.com/rebeccahughes/react-native-device-info/blob/master/android/build.gradle) is low to have the `.N` variable (https://developer.android.com/reference/android/os/Build.VERSION_CODES.html#N).

This project is using SDK 22 version, but the variable is available after SDK 24. I propose two solutions:

1) Change the N variable with a hard-coded variable as proposed in https://stackoverflow.com/a/42515931/1609620

2) Bump up the SDK version of this library to the number higher or equal than 24.

Since RN officially supports API16 and this library provides very general features, I guess the first solution is better. (I'll make a PR for this very soon, and please test it if it works on your project).

FYI. My project was not influenced by this because the global Gradle file overrides the out-dated Gradle version of sub-projects.

**Comment by ohtangza** [comment] 2018-07-27 23:44
@machour I also got noticed by https://github.com/rebeccahughes/react-native-device-info/pull/453 because the targetSdkVersion is expected to be bumped to the required version very soon.

**Comment by ghsdh3409** [comment] 2018-07-28 01:16
@reedyrm @maksim-harakhovich-itechart @kingmatusevich @tbenr @cusspvz 

I made a pull request. https://github.com/rebeccahughes/react-native-device-info/pull/460
Could you check that this change resolves this issue?

You can install this by following in `package.json`
```
"react-native-device-info": "git+https://github.com/hayanmind/react-native-device-info.git#e1899138b95bc8f71aab1877c2c2627ecab5e1c4",
```

**Comment by reedyrm** [comment] 2018-07-28 14:37
Thanks for looking into this so quickly!

I just ran #460 locally and 2 of 4 errors are gone.  I'm still encountering errors around getLocales().  I pushed the build up to travis as well to see if I get the same errors.  Once I get a result, I'll update this comment.

```
/Users/<user>/src/<userapp>/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:74: error: cannot find symbol
      current = getReactApplicationContext().getResources().getConfiguration().getLocales().get(0);
                                                                              ^
  symbol:   method getLocales()
  location: class Configuration
/Users/<user>/src/<userapp>/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:97: error: cannot find symbol
      current = getReactApplicationContext().getResources().getConfiguration().getLocales().get(0);
                                                                              ^
  symbol:   method getLocales()
  location: class Configuration
Note: /Users/<user>/src/<userapp>/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
```  

build.gradle
```
...
    compileSdkVersion 26
    buildToolsVersion "26.0.2"

    defaultConfig {
        applicationId "<userAppId>"
        minSdkVersion 16
        targetSdkVersion 26
        multiDexEnabled true
        versionCode 149
        versionName "1.1"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
...
```

**Comment by ghsdh3409** [comment] 2018-07-29 02:33
@reedyrm Thanks for letting me know! I will reflect this asap!

**Comment by ghsdh3409** [comment] 2018-07-29 05:35
@reedyrm Can you check again your project's `targetSdkVersion` and `compileSdkVersion`? It should be more than 24.

**Comment by machour** [comment] 2018-07-29 09:19
This should be fixed in 0.22.2, thank you all for your help & patience 🙏

**Comment by ghsdh3409** [comment] 2018-07-30 22:12
@eis Could you share `compileSdkVersion` of your project?

**Comment by eis** [comment] 2018-07-31 13:11
```
ext {
    compileSdkVersion = 23
    buildToolsVersion = "23.0.1"
    minSdkVersion = 16
    targetSdkVersion = 22
}
```
```
 defaultConfig {
        applicationId "censored"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 13
        versionName "0.0.13"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
```

**Comment by ohtangza** [comment] 2018-07-31 13:17
@eis It seems like you overrided the sub-projects` `compileSdkVersion` to 23 again. It's not this project's fault to break the build. Coudl I ask if there any particular reason to use the version of `23`? 

(Btw, the official RN empty projects currently make use of `26`.)

**Comment by eis** [comment] 2018-07-31 13:41
I'm not very familiar with all this - I just know that for my configuration, using 0.22.0 works but later versions won't. Has there been a change in what version this project requires or in something else?

I don't have a particular reason other than that's what I've been using for this app in the past, and changing it just for the purpose of including this project is something I don't feel compelled to, since I can just use the `0.22.0` version.

**Comment by ohtangza** [comment] 2018-07-31 14:02
@eis There was an update for supporting recent APIs for Android side in regards to `.getLocale()`. That's why the SDK version is bumped up. If you do not have a particular reason to stick to the current version. I would recommend the following (as in RN repository):

https://github.com/facebook/react-native/blob/30b9d81087cb86f5fb272d00bfee63a0632009f5/ReactAndroid/build.gradle#L251-L255

(It's from the official repository).

**Closed** 2018-08-09 21:47 UTC

**Comment by ManigandanRaamanathan** [comment] 2019-06-12 06:37
@reedyrm I'm still facing this issue in the latest version. Any solution to fix this issue?

**Comment by mikehardy** [comment] 2019-06-12 15:33
Do what the example in this repo does, and it works - it's why we have the example, to demonstrate + prove it works
