### ISSUE TITLE
No Compile on iOS `ld: library not found for -lRNDeviceInfo-tvOS`

### ISSUE THREAD

**Issue by ercpereda** [rebeccahughes/react-native-device-info#286] opened 2017-12-19 20:22 UTC

**Comment by pqminh** [comment] 2017-12-20 08:23
me too

**Comment by bjacog** [comment] 2017-12-21 11:35
Same issue here, can work around this by running 0.12.1.

**Comment by TrustTheBoy** [comment] 2017-12-22 09:51
me too

**Comment by TheLittleBlack** [comment] 2018-01-30 03:41
楼上6666

**Comment by machour** [comment] 2018-02-03 10:15
Is this still happening on 0.14.0? We did ship some additional tvOS fixes

**Comment by machour** [comment] 2018-02-03 16:23
Yes it is. Closing this issue as it's a duplicate of #258

**Closed by machour** 2018-02-03 16:23 UTC
Labels: bug, ios
