### ISSUE TITLE
method does not override or implement a method from a supertype   @Override                     

### ISSUE THREAD

**Issue by shaharyar123** [rebeccahughes/react-native-device-info#213] opened 2017-09-06 11:54 UTC
i have updated react-native version from **0.44.0** to **0.48.1**, after which i am unable to make a build. it is giving this error 
```
myapp\node_modules\react-native-device-info\android\src\main\java\com\learnium\RNDeviceInfo\RNDeviceInfo.java:26: error: method does not override or implement a method from a supertype
  @Override                                                          
  ^
1 error                                                              
:react-native-device-info:compileReleaseJavaWithJavac FAILED         

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-device-info:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by antoxann96** [comment] 2017-09-06 12:30
Same for me, updated to RN 0.47.2

**Comment by MrFlox** [comment] 2017-09-10 18:42
Same for me, update to RN 0.48.2

**Comment by alexeyMohnatkin** [comment] 2017-09-13 15:13
try `yarn upgrade react-native-device-info`
It solved the issue for me

**Comment by modularity** [comment] 2017-10-11 00:58
Same error for RN 0.48.4 with react-native-device-info@0.10.2

I think the problem is that npm is pulling 0.10.2, but for RN 0.47+ we need 0.11+. The docs mention this, but maybe react-native-device-info should by default point to 0.11.0 instead. To fix it, I ran react-native unlink react-native-device-info && npm uninstall react-native-device-info, followed by npm install --save react-native-device-info@0.11.0 and finally react-native link react-native-device-info.

**Comment by MacKentoch** [comment] 2017-10-22 13:51
It is a known issue **easy fixed**.

It is due to a RN breaking change so just remove `@overrides` in `RNDeviceInfo.java`

**What is wronf:**

```java
public class RNDeviceInfo implements ReactPackage {

  @Override
  public List<NativeModule> createNativeModules(
                              ReactApplicationContext reactContext) {
    List<NativeModule> modules = new ArrayList<>();

    modules.add(new RNDeviceModule(reactContext));

    return modules;
  }

  @Override
  public List<Class<? extends JavaScriptModule>> createJSModules() {
  	return Collections.emptyList();
  }

  @Override
  public List<ViewManager> createViewManagers(
                            ReactApplicationContext reactContext) {
  	return Collections.emptyList();
  }

}
```

**replace with:**

```java
public class RNDeviceInfo implements ReactPackage {


  public List<NativeModule> createNativeModules(
                              ReactApplicationContext reactContext) {
    List<NativeModule> modules = new ArrayList<>();

    modules.add(new RNDeviceModule(reactContext));

    return modules;
  }


  public List<Class<? extends JavaScriptModule>> createJSModules() {
  	return Collections.emptyList();
  }


  public List<ViewManager> createViewManagers(
                            ReactApplicationContext reactContext) {
  	return Collections.emptyList();
  }

}
```

**Comment by balajivenkatesh** [comment] 2018-01-17 04:34
Is this fixed here?

**Comment by machour** [comment] 2018-02-14 14:49
Yes it is, the @Override statement was removed a while ago.

**Comment by machour** [comment] 2018-02-14 14:50
(Fixed in 0.11.0 in fact)

**Closed by machour** 2018-02-14 14:49 UTC

**Comment by niranjan-b-prajapati** [comment] 2018-05-15 12:57
I am on RN 0.44 but still its giving me the same error while creating the release build. can some one help me with this issue.

**Comment by manuTro** [comment] 2018-05-15 14:37
now I got this error for the first time.. yesterday was ok.. I'm using react-native 0.44

**Comment by angeloocana** [comment] 2018-05-15 15:49
@manuTro me too, until yesterday everything was OK.

react-native 0.44.3

**Comment by manuTro** [comment] 2018-05-15 15:53
@angeloocana for me isn't just this library.. but also other 5 libraries.. I don't know what happened..

**Comment by angeloocana** [comment] 2018-05-15 15:57
@manuTro  Yes all the libraries for me too!!! 
I think is something that is downloaded on the fly in `react-native run-android`

=/

**Comment by manuTro** [comment] 2018-05-15 16:04
@angeloocana I'm gonna to open an issue on react-native page

**Comment by guerjon** [comment] 2018-05-15 16:42
Same happen here, i went to my home yesterday came back today at morning and get this error.

**Comment by ashksmith** [comment] 2018-05-15 16:49
Same happened here, no changes to node_modules and started to get errors.

**Comment by guerjon** [comment] 2018-05-15 17:02
Got this on android, React-native 0.44.3, no changes at the node_modules since yesterday.

**Comment by niranjan-b-prajapati** [comment] 2018-05-15 17:41
i added this to my build.gradle in app folder 
compile ("com.facebook.react:react-native:0.44.0") { force = true }

still the same error while creating release build.

**Comment by JustinKasad** [comment] 2018-05-15 22:01
This fixed it for me:
https://github.com/facebook/react-native/issues/19272#issuecomment-389321642

**Comment by niranjan-b-prajapati** [comment] 2018-05-16 06:53
@JustinKasad  tried the solution you mentioned but still its not working for me. Is anyone still facing the issue ?

**Comment by manuTro** [comment] 2018-05-16 08:47
https://github.com/facebook/react-native/issues/19272#issuecomment-389405958 fixed for me by using react-native 0.44.3

**Comment by ashksmith** [comment] 2018-05-16 09:07
Upgrading is not possible for me; My fix was to target my version in build.gradle

**Comment by niranjan-b-prajapati** [comment] 2018-05-16 09:08
@ashksmith exactly same here, not possible to upgrade as the app is going for production.

**Comment by ashksmith** [comment] 2018-05-16 09:16
@niranjan-b-prajapati  [This worked for me](https://github.com/facebook/react-native/issues/19259)

**Comment by niranjan-b-prajapati** [comment] 2018-05-16 10:56
@ashksmith  i tried both solutions mentioned in the link but both of them not working in my case. :-(

**Comment by Hemanth1985** [comment] 2018-05-16 11:30
I have been facing the same issue since yesterday RN 0.44.0

**Comment by nadirHomeFriend** [comment] 2018-05-16 12:36
hello,
after applying the code below to my build.gradle , react-native-system-notification does not work when forcing react-native 0.46 . i have seen in build.gradle of system notification module and see that he is using 0.19.+ as react native version . so forcing the react native version is not working for modules which need lower versions .
please help
subprojects {
configurations.all {
resolutionStrategy {
force 'com.facebook.react:react-native:0.46.4'
}
}
}

this is dependencies of react-native-system-notification:
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.facebook.react:react-native:0.19.+' => here we can see the use of lower version
    compile 'com.google.code.gson:gson:2.3.+'
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:support-annotations:+'
    compile 'com.google.android.gms:play-services-gcm:8.1.0+'
    compile files('libs/js.jar')
}

**Comment by niranjan-b-prajapati** [comment] 2018-05-17 07:05
@machour People are still facing issues, This issue can't be closed.

**Comment by machour** [comment] 2018-05-17 10:30
@niranjan-b-prajapati it's an 8 month old issue which was fixed, so this is why it was closed, way before your first comment here.

Feel free to open a new issue thoug :)

**Comment by niranjan-b-prajapati** [comment] 2018-05-17 10:37
@machour ok

**Comment by yusuf987** [comment] 2018-06-01 09:21
MacKentoch  answer worked for me

**Comment by niranjan-b-prajapati** [comment] 2018-06-01 12:54
Unfortunately my problem was resolved by deleting node modules folder and running Yarn command again. It was very weird knowing there were no changes made in node modules.

**Comment by davidvenin** [comment] 2018-07-02 11:55
removing override worked for me as well :)

**Comment by mariraj-mitosis** [comment] 2018-07-25 12:17
Execution failed for task ':react-native-deviceinfo:compileReleaseJavaWithJavac'
Error in react-native 0.55.4

**Comment by ClickHere0521** [comment] 2021-03-21 18:40
Thanks. This is a really good discussion. I had the same error, but now it works.
