### ISSUE TITLE
getBatteryLevel show me if device is charging

### ISSUE THREAD

**Issue by dominicrico** [rebeccahughes/react-native-device-info#387] opened 2018-04-17 14:45 UTC
## Description

I would like to see if the device is currently charging or not when I do getBatteryLevel(). The promise could return 2 for charging

## Use Case

I  build two apps at the moment, one is a "controller" the other is an "updater". The updater is paired with a controller. The controller shows a list of connected devices and if a device has low battery I show a notification. Would be nice to see on my controller "device dashboard" which devices are currently charging.

**Comment by dominicrico** [comment] 2018-04-20 11:33
Hey, would also be ok or getBatteryLevel() could return an Object like:
```
{level: 0.44, charging: true}
```

**Comment by dominicrico** [comment] 2018-04-20 12:29
@machour I got a PR ready with the above mentioned object.

**Comment by machour** [comment] 2018-04-20 12:31
The problem is that this would cause a compatibility break for people currently using this method. 
Also, it doesn't really make sense to getBatteryLevel to return anything else than the level. 
Any problems changing your PR to do this in a new method?

**Comment by dominicrico** [comment] 2018-04-23 07:35
@machour nope, I can do this and provide a new method.

**Comment by mikehardy** [comment] 2019-03-10 20:13
@machour closable - already merged as #514

**Closed** 2019-03-10 20:37 UTC
Labels: feature-request, help wanted
