### ISSUE TITLE
Timezone is not a function

### ISSUE THREAD

**Issue by prashen** [rebeccahughes/react-native-device-info#101] opened 2016-10-02 18:28 UTC
Plugin is not working for me: showing error 
timezone is not function. My package.json dependencies are following:
"dependencies": {
    "react": "15.3.2",
    "react-native": "0.34.1",
    "react-native-device-info": "^0.9.5"
  }

**Comment by yannickoo** [comment] 2016-10-05 20:08
Duplicate of #98 😇

**Comment by prashen** [comment] 2016-10-11 17:22
Is there any solution :)

**Comment by yannickoo** [comment] 2016-10-11 17:40
You can adjust your `package.json` by changing following:

`^0.9.5` ➡️  `git+https://github.com/rebeccahughes/react-native-device-info`

**Comment by prashen** [comment] 2016-10-11 18:50
But I am using "react-native-device-info": "^0.9.5" already.

**Comment by yannickoo** [comment] 2016-10-11 20:48
Sorry @prashen but this is not enough. Timezone landed in 92c94a115c9a1a67a7cdff1edc852fbca3655600 which is actually after `0.9.5`. We need to wait for a new version or you simply use `master` in the meanwhile by changing the entry in your `package.json` as described above.

<img width="637" alt="screen shot 2016-10-11 at 22 46 30" src="https://cloud.githubusercontent.com/assets/1086961/19288103/c3c8de0e-9004-11e6-9ee1-4489e6123b23.png">
(the `bump version numbers` commit was the change to `0.9.5`)

**Comment by GantMan** [comment] 2016-10-11 21:21
I'll try to get us a new version released soon.  Just haven't had the time to test on devices :)  It's not easy.

**Comment by GantMan** [comment] 2016-10-17 21:31
version 0.9.6 published

**Comment by krishbhattacharyya** [comment] 2016-12-14 13:33
Hi @prashen , 
You should close this issue ... It is already working.

**Closed** 2016-12-14 17:28 UTC
