### ISSUE TITLE
RCTBridge required dispatch_sync to load RCTDevLoadingView. This may lead to deadlocks

### ISSUE THREAD

**Issue by courptwayne** [rebeccahughes/react-native-device-info#429] opened 2018-06-06 09:34 UTC
## Summary

|             |     |
| ----------- | --- |
| Version     | ?   |
| Affected OS | ?   |
| OS Version  | ?   |

**Comment by machour** [comment] 2018-06-06 09:35
Duplicate of #260

**Closed by machour** 2018-06-06 09:35 UTC
