### ISSUE TITLE
react native link doesn't do everything that's necessary for this to run. 

### ISSUE THREAD

**Issue by cbartondock** [rebeccahughes/react-native-device-info#182] opened 2017-06-12 01:36 UTC
I had to go into my android folder and add 
`compile "com.google.android.gms:play-services-base:+"`
`compile "com.google.android.gms:play-services-maps:+"`
to app/build.gradle

I was getting a crash with no errors in react-native log-android, I had to run adb logcat and solved it via [react-native-maps/818](https://github.com/airbnb/react-native-maps/issues/818)

I assume this should be done automatically when one runs "react-native link"

**Comment by machour** [comment] 2018-02-14 14:55
Hi @cbartondock, is this still happening with our last release?
Possible dupe of #177

**Comment by machour** [comment] 2018-02-22 09:09
Closing this as no feedback was provided.

**Closed by machour** 2018-02-22 09:09 UTC
Labels: android, feedback-requested
