### ISSUE TITLE
Could not find runtime.jar (android.arch.lifecycle:runtime:1.0.0)

### ISSUE THREAD

**Issue by haiifeng** [rebeccahughes/react-native-device-info#415] opened 2018-05-28 11:00 UTC
## Summary
| Version |
    "native-echarts": "^0.4.0",
    "react": "~15.4.0-rc.4",
    "react-native-device-info": "^0.21.5"
| OS Version |
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    

## Current behavior
![deviceinfo](https://user-images.githubusercontent.com/20502943/40611551-564d7438-62a9-11e8-83e9-c73e4632004f.png)
today i build android and find that problem, and i can't solve it.

**Comment by machour** [comment] 2018-05-28 11:51
Dupe of #414.

**Closed by machour** 2018-05-28 11:51 UTC
