### ISSUE TITLE
undefined is not object (evaluating 'RNDeviceInfo.deviceId')

### ISSUE THREAD

**Issue by jurajkrivda** [rebeccahughes/react-native-device-info#52] opened 2016-06-14 00:11 UTC
var DeviceInfo = require('react-native-device-info');
console.log(DeviceInfo.getDeviceId());

Android 5.1

**Comment by heyalexchoi** [comment] 2016-06-14 19:34
having a similar issue. in my case DeviceInfo seems to not be importing properly.

<img width="586" alt="screen shot 2016-06-14 at 3 34 29 pm" src="https://cloud.githubusercontent.com/assets/4961047/16056880/7fa31c20-3245-11e6-8575-de01144a81f4.png">

**Comment by spukhov** [comment] 2016-07-10 10:04
The same story. Android 6.0.

**Comment by mehcode** [comment] 2016-07-10 16:07
That error happens when the java module is not being loaded somehow. 

Make sure that you've done ALL of https://github.com/rebeccahughes/react-native-device-info#installation-android.

After doing the above, do a "Clean" then "Run".

**Comment by alma-socar** [comment] 2016-07-21 05:00
Same issue here for iOS

```
2016-07-21 13:57:23.197 [error][tid:com.facebook.react.JavaScript] undefined is not an object (evaluating 'RNDeviceInfo.uniqueId')
```

**Comment by heyalexchoi** [comment] 2016-07-21 14:52
I fixed my issue by relinking the native dependency. It was improperly linked (or its linking wasn't properly checked into .pbxproj) so I suppose it was undefined at runtime.

**Comment by manupytwn** [comment] 2016-07-26 18:33
"react": "15.2.1",
    "react-native": "^0.29.2",
    "react-native-contacts": "0.2.8",
    "react-native-device-info": "^0.9.3"

In my case the problem appears when I try to configure "react-native-device-info" from "pod install". A version of React (0.11.0) is installed and duplicate symbols:

duplicate symbol _OBJC_METACLASS_$_RCTNavigatorManager in:
    /Users/manupytwn/GitHub/TheApp/ios/build/Debug-iphonesimulator/libReact.a(RCTNavigatorManager.o)
    /Users/manupytwn/GitHub/TheApp/node_modules/react-native/React/build/Debug-iphonesimulator/libReact.a(RCTNavigatorManager.o)
ld: 458 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by krishbhattacharyya** [comment] 2016-08-17 07:22
Hi, 
The same problem arise to me.  Is there any solution?
![screenshot from 2016-08-12 12 39 05](https://cloud.githubusercontent.com/assets/10433734/17727788/3017b754-6479-11e6-9b27-17f9faf8d213.png)

**Comment by manupytwn** [comment] 2016-08-25 07:15
My solution was to downgrade react and react-native:

    "react": "0.14.8",
    "react-native": "0.25.1",
    "react-native-contacts": "0.2.8",
    "react-native-device-info": "^0.9.3"

Good luck!

**Comment by krishbhattacharyya** [comment] 2016-08-25 18:09
Thanks @manupytwn I will try it very soon.

**Comment by Ascendance** [comment] 2016-09-16 16:44
Exactly the same problem. Ran it last night it was okay. This morning this error magically appeared.

**Comment by goodhyun** [comment] 2016-10-08 17:53
First I got this error on the red screen, but after I rebuilt all again, my android app started to force-close. to make matters worse...

**Comment by afilp** [comment] 2016-10-11 12:19
Hi, I get the same error on Android, when running "react-native run-android" on a device:

MainApplication.java:41: error: cannot find symbol
          new RNDeviceInfo(),

Is there any solution imminent? We cannot release without this unfortunately (because it works on iOS but not on Android...)

**Comment by itcurves** [comment] 2016-10-14 16:50
Anyone found a solution? I am getting the same error on Android and I have to upload the application ASAP.

**Comment by jorge8989** [comment] 2016-10-18 01:07
I had the same issue after installing the module witn npm. It seems like the problem was that i didn't link the module https://github.com/rebeccahughes/react-native-device-info/#automatically-link . I solved the problem running `react-native link react-native-device-info` . I'm running my app on an actual device using `react-native run-android`

**Comment by breadadams** [comment] 2016-10-19 16:03
As @jorge8989 said, running `react-native link react-native-device-info` it works again. However you have to restart the app after running this, quit the simulator and then run `react-native run-ios`again.

**Comment by itcurves** [comment] 2016-10-19 20:37
@breadadams  I did that but still getting the same error I am using RN 0.34 and it run perfectly fine on iOS only android have this issue.

**Comment by breadadams** [comment] 2016-10-20 22:00
Hmm, that's weird @itcurves. I'd only tested on iOS so far, but just ran on android (simulator) & working fine there too. Maybe it's an incompatibility? The app I'm testing on is pretty barebones at the mo' - just some default react-native components & some firebase connections.

**Comment by itcurves** [comment] 2016-10-22 05:51
Yes @breadadams  it is. Look at this I just try to link again:

rnpm-install info Android module react-native-device-info is already linked 
rnpm-install info iOS module react-native-device-info is already linked 

but still same error:

Cannot read property 'uniqueId' of undefined
Object.getUniqueID
    deviceinfo.js:11
new
    index.android.bundle?platform=android&dev=true&hot=false&minify=false:80800:42
ReactCompositeComponentWrapper._constructComponentWithoutOwner
    ReactCompositeComponent.js:296
ReactCompositeComponentWrapper._constructComponent
    ReactCompositeComponent.js:278
ReactCompositeComponentWrapper.mountComponent
    ReactCompositeComponent.js:190
Object.mountComponent
    ReactReconciler.js:47
Constructor.mountChildren
    ReactMultiChild.js:240
Constructor.initializeChildren
    ReactNativeBaseComponent.js:69
Constructor.mountComponent
    ReactNativeBaseComponent.js:187
Object.mountComponent
    ReactReconciler.js:47

**Comment by LironHazan** [comment] 2016-11-05 10:43
Had the same issue (runnig on ios real device) and re-linking solved for me, why "relinking"? cause apparently my trying to link it manually effected so I ran: react-native unlink react-native-device-info and afterwards react-native link react-native-device-info

**Comment by xiaoleiooo** [comment] 2016-12-06 09:41
I had the same problem.The solve way I use is： 
Open your Xcode or AndroidStudio，then clean and build your project，last run app.

**Comment by jinxac** [comment] 2017-01-12 10:16
After Linking I got this:-

```
relay-react-native-app aragorn$ react-native link react-native-device-info
rnpm-install info Linking react-native-device-info android dependency
rnpm-install info Android module react-native-device-info has been successfully linked
rnpm-install info Linking react-native-device-info ios dependency
rnpm-install info iOS module react-native-device-info has been successfully linked
```

But still error was coming. So I cleaned the project and build it again. Works fine.

**Comment by ThunderDev1** [comment] 2017-03-04 17:37
I have a similar error on android device (**works ok in emulator**):

undefined is not an object (evaluating 'RNDeviceInfo.deviceLocale')

Have double checked [https://github.com/rebeccahughes/react-native-device-info#installation-android](https://github.com/rebeccahughes/react-native-device-info#installation-android)

When I run `react-native link react-native-device-info` is says module is already linked

Any ideas ?

**Comment by holgersindbaek** [comment] 2017-03-20 19:47
I've got the same issue. @ThunderDev1 solution didn't work for me. Any other suggestions?

**Comment by holgersindbaek** [comment] 2017-03-21 20:24
I've tried all the suggestions above and I'm still getting the same error. Does everyone still have this issue after it was first reported almost a year ago? Nobody found the cause of the bug?

**Comment by kmakihara** [comment] 2017-04-05 02:41
Developing in Expo and none of the previous solutions have helped. Any suggestions?

**Comment by encorex** [comment] 2017-04-05 14:33
Same problems also with Expo....

**Comment by GantMan** [comment] 2017-04-05 14:35
did you eject from Expo?  So you have an ios/android project?

**Comment by Adamnator92** [comment] 2017-04-20 07:20
make sure your in your android file `MainApplication.java`
`
 @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
+         new RNDeviceInfo(),
          new MainReactPackage()
      );
    }
`

**Comment by tronin** [comment] 2017-05-05 08:36
I had linked package manually and fixed it. 

Thank you for the great plugin!

**Comment by Khalidxx** [comment] 2017-06-28 03:51
I tried everything suggested here and I still have the same issue. Is there no other solution?

**Comment by shenkimaro** [comment] 2017-07-27 04:04
For me works when I recreate the project with react-native init project, after I install the react-native-device-info and works. So then I copy all code to the new directory.

**Comment by Lawrence23** [comment] 2017-07-27 10:08
I am using expo and none of the above solutions worked for me

**Comment by tronin** [comment] 2017-07-27 10:28
@Lawrence23 try 
```
$ react-native link react-native-device-info
```

**Comment by Lawrence23** [comment] 2017-07-28 14:02
Tried that. Didn't work

**Comment by jiteshwadia** [comment] 2017-08-03 06:11
react-native link OR react-native link react-native-device-info.
@Lawrence23 
After that close any previously running react packager. Don't just simply reload the app.

Now run it.  This fixed in my case.

**Comment by bencodezen** [comment] 2017-08-15 20:25
@jiteshwadia Are you using Expo? It seems like that may be the issue. I'm not able to link it using Expo either.

**Comment by jiteshwadia** [comment] 2017-08-16 09:05
@bencodezen , No, I am not using Expo

**Comment by bencodezen** [comment] 2017-08-16 12:10
@kmakihara @Lawrence23 @encorex 

For Expo users, it seems like this library isn't compatible as far as I can tell. The workaround for this is to use Expo Constants https://docs.expo.io/versions/latest/sdk/constants.html. Hope this helps future Expo users trying to use this library!

**Comment by betoharres** [comment] 2017-09-13 00:52
Same here, I just createad a fresh new project and then tried to use it on iOS emulator and failed with this message..

Is this a particular OS problem or is something with the library?

**Comment by betoharres** [comment] 2017-09-13 01:01
I got it working after linking it again(for some reason you need to do 2x) and shut down any open process.

**Comment by davebro** [comment] 2017-10-08 16:29
For those facing this on iOS, the complete steps for me were to:

Shut down packager
Uninstall app from simulator
Shut down simulator
Run `react-native unlink react-native-device-info`
Run `react-native link react-native-device-info`
Open project in Xcode, clean and build
Start packager `react-native-start`
Start the simulator `react-native run-its --simulator "iPhone 8 Plus"` or whichever simulator you use

It then worked no problem. Really not sure what the actual issue was, my guess is that the package was not properly linked. (I always use `react-native link`)

**Comment by erwan-lcs** [comment] 2017-10-17 10:53
Thanks @bencodezen for the workaround, my code snippet for those trying to use react-native-device-info with Expo


```
    var deviceSerial =0;
    try {
        if(Expo.Constants.appOwnership == 'expo')
        {
            console.log('Running in expo');
            deviceSerial = Expo.Constants.deviceId;
        }
        else
        {
            var DeviceInfo = require('react-native-device-info');
            deviceSerial = DeviceInfo.getUniqueID();
        }
         console.log('DEVICE ID FOUND: '+deviceSerial);
    }
    catch(e)
    {
        console.log('error reading device ID');
        deviceSerial =1;
    }
```

**Comment by chiragpurohit71085** [comment] 2017-10-28 18:58
In my case 

libRNDeviceInfo.a
was missing in Link Library With Binary  (Build phases)

**Comment by dann1609** [comment] 2018-02-07 04:16
In my case I import node_modules/react-native-device-info/RNDeviceInfo.xcodeproj to libraries inside Xcode project. then link libRNDeviceinfo.a to build phases then build project from Xcode.

![captura de pantalla 2018-02-06 a la s 11 14 47 p m](https://user-images.githubusercontent.com/7472461/35898296-be811978-0b93-11e8-85a1-217ffa4c84ee.png)
![captura de pantalla 2018-02-06 a la s 11 15 51 p m](https://user-images.githubusercontent.com/7472461/35898298-bfcc5d38-0b93-11e8-83fd-07151427b414.png)

**Comment by machour** [comment] 2018-02-14 14:04
Closing this old issue which became a melting pot of ios/android build issues..
If anyone still face this problem, please submit a new issue.

**Closed by machour** 2018-02-14 14:04 UTC

**Comment by sterswift** [comment] 2018-05-16 07:08
@bencodezen Saved me, thank you very much!

**Comment by bakedbird** [comment] 2018-07-13 10:10
For anyone still having this issue even after following the manual linking steps.

- Go to MainApplication.java
- Delete `new RNDeviceInfo()` from `getPackages()`
- Add `getPackages()` inside `createAdditionalReactPackages()`

In case you don't have `createAdditionalReactPackages()` in your `MainApplication.java`, here is the code:

```
public class MainApplication extends NavigationApplication {
    ...
    @Override
    public List<ReactPackage> createAdditionalReactPackages() {
        return Arrays.<ReactPackage>asList(
                // eg. new VectorIconsPackage()
                new RNDeviceInfo()
        );
    }
    ....
}
```

**Comment by yusuf987** [comment] 2019-01-26 06:59
thanks chiragpurohit71085 your  solution worked for me

**Comment by mikehardy** [comment] 2019-03-15 14:46
This issue is popular, but it is always an installation/configuration issue. There is a clean example in the repository built following the instructions and working well. If you can reproduce your problem in the example, open a new issue. If not, then study the example again to see how to integrate things and make sure you followed the instructions...

**Comment by Bill-Niz** [comment] 2019-04-04 08:22
> Commenting on @bakedbird fix. I had the problem where the Main Application never created a new instance for RNDdeviceInfo().
> 
> I fixed it by adding it in RNDeviceInfo into the following code in MainActivity. Please note I changed my java file to use kotlin and dont forget to `import com.learnium.RNDeviceInfo.RNDeviceInfo`
> 
> ```
> override fun getPackages(): List<ReactPackage> {
>             return Arrays.asList(
>                     MainReactPackage(),
>                     FastImageViewPackage(),
>                     PlayerPackage(),
>                     RNDeviceInfo(),
>                     RNI18nPackage()
>             )
>         }
> ```

Ho man!! Wasted 3 days on this!!
Thank you!!

**Comment by CoryWritesCode** [comment] 2019-09-24 16:18
If anyone is still having issues with this I found that I had this issue when upgrading from `v2.2.2` to `v3.1.4` and noticed the function name change in [this beta version](https://github.com/react-native-community/react-native-device-info/blob/master/CHANGELOG.md#300-beta1) from `getDeviceID` to `getDeviceId`. Changing this, and rebuilding worked for me.

**Comment by mikehardy** [comment] 2019-09-24 21:22
@CoryWritesCode if you haven't seen https://github.com/react-native-community/react-native-device-info/wiki/V2-to-V3-Migration-Guide you should check it out - there were quite a few moves, but all documented with the from what -> to what

**Comment by digitaluniverse** [comment] 2019-09-25 02:31
@CoryWritesCode I would have never noticed this thank you

**Comment by mikehardy** [comment] 2019-09-25 02:35
@digitaluniverse most of the API name changes are similarly subtle re-capitalizations - please look at the inventory on the v2->v3 page, I would hate for anyone else to waste any more time than needed

**Comment by CoryWritesCode** [comment] 2019-09-25 12:53
@mikehardy Thanks for the link! I had not seen that at all. Might be good to have that linked on the README.

**Comment by mikehardy** [comment] 2019-09-25 14:27
@CoryWritesCode oh dang - I thought I did? It is definitely in the changelog, but you're right. The more linkage the better - the v3 release is breaking but it is not supposed to suck as an upgrade :-)
