### ISSUE TITLE
Invalid path: /storage/emulated/0

### ISSUE THREAD

**Issue by jslok** [rebeccahughes/react-native-device-info#320] opened 2018-02-11 22:48 UTC
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.15.1   |
| Affected OS | Android   |
| OS Version  | seen on 7.1, 7, 6, 4.22 so far  |

## Current behavior

App crashes on start for some users. I'm seeing this error in Bugsnag:

com.facebook.react.common.JavascriptException Java exception in 'NativeModules'

java.lang.IllegalArgumentException: Invalid path: /storage/emulated/0, stack:
android.os.StatFs.doStat@46
android.os.StatFs.<init>@39
com.learnium.RNDeviceInfo.RNDeviceModule.getFreeDiskStorage@137
com.learnium.RNDeviceInfo.RNDeviceModule.getConstants@224
com.facebook.react.bridge.JavaModuleWrapper.getConstants@140
android.os.Handler.handleCallback@751
android.os.Handler.dispatchMessage@95
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage@31

## Expected behavior

App should start normally. As far as I can tell, 0.14.x and the issue only started happening on 0.15.x.

Any help would be much appreciated.

**Comment by machour** [comment] 2018-02-12 10:53
Hi @jslok and thank you for reporting this issue. `getFreeDiskStorage()` was indeed added in 0.15.0 and [this line](https://github.com/rebeccahughes/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L137) seems to be the culprit.

Are you able to reproduce the issue on your own?

**Comment by jslok** [comment] 2018-02-12 10:58
@machour Unfortunately I cannot reproduce it. It does not seem to affect many users so far. One user said he was able to solve the issue on his own by uninstalling then reinstalling my app several times but of course that is not really a good solution.

**Comment by machour** [comment] 2018-02-12 11:01
of course it's not. Maybe surrounding the block with a try/catch could help. 
Do you want to open a PR with this solution?

**Comment by jslok** [comment] 2018-02-12 11:08
@machour you can go ahead and take care of it if you dont mind.

**Comment by jslok** [comment] 2018-02-12 11:08
Still new to git and never done a pr before.

**Comment by machour** [comment] 2018-02-12 11:23
I could do it, but I can also help you out doing your first PR ever, and I think this would be even cooler for you and it would definitely make my day 😄 

> give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime

Basically you would do the following:

- fork this repository into your account: 
<img width="990" alt="screen shot 2018-02-12 at 12 12 55 pm" src="https://user-images.githubusercontent.com/304450/36094359-300b6356-0fee-11e8-8acf-2cb8a1ec8c80.png">

- clone your fork: 
 `git clone git@github.com:jslok/react-native-device-info.git`

- create a new branch to work on:
`git checkout -b 320-fix-getfreediskspace`

- make your changes
- commit your change with a meaningful message:
```
git commit -m "fix: surround StatsFS call with try/catch" android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java
```

- push the changes to your branch:
```
git push --set-upstream origin 320-fix-getfreediskspace
```

- head over to your fork on GitHub, you should see a yellow box like this:
<img width="1007" alt="screen shot 2018-02-12 at 12 19 57 pm" src="https://user-images.githubusercontent.com/304450/36094563-14858e3a-0fef-11e8-95ef-cce78c544167.png">

- click on "Compare & pull request"

- validate the changes on next screen (make sure you fill the PR template)

- Get you first Pull Request ever merged, then brag about it to your friends ❤️ 

PS: I'm available on Twitter or Gitter if you need assistance.

**Comment by jslok** [comment] 2018-02-12 12:34
Ok!! Hope I did it right and thank you for the detailed instructions. Let me know if there's anything wrong with it. I shall be much more helpful on github from now on.

**Comment by machour** [comment] 2018-02-12 12:48
This is so great, thank you for the pull request! 🎉 🎉 🕺 
I left you some remarks there that needs taking care of.

**Closed** 2018-02-13 01:14 UTC
Labels: android, bug, has PR
