### ISSUE TITLE
isTablet returns true for google pixel 

### ISSUE THREAD

**Issue by KunwarSingh** [rebeccahughes/react-native-device-info#275] opened 2017-12-01 16:59 UTC
DeviceInfo.isTablet() is returning true on GooglePixel

* Library version = 0.10.1
* RN version = 0.43.0

**Comment by machour** [comment] 2018-01-30 11:04
The problem is that tablet detection have become harder & harder with new phones having extra high definitions..

**Comment by machour** [comment] 2018-02-03 08:48
Duplicate of #198

**Closed by machour** 2018-02-03 08:48 UTC
