### ISSUE TITLE
Failed on android with com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzpq;

### ISSUE THREAD

**Issue by itinance** [rebeccahughes/react-native-device-info#102] opened 2016-10-08 20:43 UTC
On Android gradles build process gives the following exception:

```
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzpq;
Unknown source file :   at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file :   at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file :   at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file :   at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file :   at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file :   at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file :   at com.android.dx.command.Main.main(Main.java:106)

```

When removing react-native-device-info-stuff from build.gradle, settings.gradle and MainActivity.java, everything works fine.

**Comment by ospfranco** [comment] 2016-10-26 01:58
I'm having this same problem, did you find any way to fix it?

**Comment by itinance** [comment] 2016-10-26 08:21
Not yet

**Comment by kompot** [comment] 2016-12-27 15:30
Did you try `./gradlew clean`?

**Comment by ospfranco** [comment] 2016-12-28 14:34
Dex issues are caused by conflicting dependencies between libraries, from my experience very hard to track, one option as @kompot says is try 

`./gradlew clean`

However if this does not solve your problem you need to go through each of your dependencies and check for conflicts, if I remember correctly in my case it was a sub-dependency on google play services, and try to force a specific version in the gradle build settings.

**Comment by skymax406** [comment] 2017-01-27 08:51
Resolve with that in android/app/build.gradle : 

```java
compile (project(':react-native-device-info')){
       exclude group: "com.google.android.gms" 
}

**Comment by Nodonisko** [comment] 2017-03-01 22:57
I write whole article about this problem:
[https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f#.9l0u84y9t](https://medium.com/@suchydan/how-to-solve-google-play-services-version-collision-in-gradle-dependencies-ef086ae5c75f#.9l0u84y9t)

Hope I helped you :)

**Comment by machour** [comment] 2018-02-23 16:03
This is now mentioned in the [troubleshooting section](https://github.com/rebeccahughes/react-native-device-info#troubleshooting) of the README file.

Closing this issue.

**Closed by machour** 2018-02-23 16:03 UTC
Labels: :book: docs, :robot: android
