### ISSUE TITLE
About Could not find support-v4.aar (com.android.support:support-v4:26.1.0)

### ISSUE THREAD

**Issue by vitrum** [rebeccahughes/react-native-device-info#414] opened 2018-05-28 10:16 UTC
Try this:

https://stackoverflow.com/questions/45103230/failed-to-resolve-com-android-supportcardview-v726-0-0-android

1, In project build.gradle, add 

       maven {
            url "https://maven.google.com"
        }

in allprojects

Will look like:

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
    }
}

2. clean gradlew

cd android && ./gradlew clean

**Comment by rahmanmarija** [comment] 2018-05-28 10:21
It's not working, it outputs different error
**problem occurred configuring project ':react-native-device-info'.
      > Could not find common.jar (android.arch.core:common:1.0.0).
        Searched in the following locations:
            https://jcenter.bintray.com/android/arch/core/common/1.0.0/common-1.0.0.jar**

**Comment by vitrum** [comment] 2018-05-28 10:27
Try add "google()" in repositories.

This is my build.gradle now:

    allprojects {
        repositories {

            mavenLocal()
            google()
            jcenter()
            maven {
                url 'https://maven.google.com'
            }
            maven {
                // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
                url "$rootDir/../node_modules/react-native/android"
            }
        }
    }

**Comment by cihadturhan** [comment] 2018-05-28 10:27
Seems like my day is wasted with this error and still couldn't understand what the issue is. 
When I check the link on browser it downloads the jar file.

**Comment by a396901990** [comment] 2018-05-28 10:30
not work for me

**Comment by windydang26** [comment] 2018-05-28 10:30
with me:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-device-info'.
      > Could not find runtime.jar (android.arch.lifecycle:runtime:1.0.0).

**Comment by vigneshw1995** [comment] 2018-05-28 10:31
+1

**Comment by XHTeng** [comment] 2018-05-28 10:31
+1

**Comment by xSmoggeRx** [comment] 2018-05-28 10:46
I tried put google() before jcenter() and also use url 'https://maven.google.com' instead the previous url I had and nothing works for me. I hope this should be fixed.

**Comment by vdumontier** [comment] 2018-05-28 10:49
Ok worked for me, thanks @cihadturhan 

Just set 

`        maven {
            url 'https://maven.google.com'
        }`

**Before**  the    jcenter() and everything is OK.

`
allprojects {
    repositories {
        mavenLocal()
        maven {
            url 'https://maven.google.com'
        }
        jcenter()
        maven {
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
`

**Comment by Geoffrey-D** [comment] 2018-05-28 10:49
thanks @cihadturhan, it also worked for me

**Comment by xSmoggeRx** [comment] 2018-05-28 11:08
A lot of thanks @vdumontier, you explained how it should be, the problem is that I was replacing instead of adding the new maven. I'm who ask it for StackOverFlow. Thanks again and hope it doesn't happen again! 💃

**Comment by xwartz** [comment] 2018-05-28 11:43
@cihadturhan  
It worked for me, thanks very much.

**Comment by Richi2293** [comment] 2018-05-28 12:06
Doing that way to me brings this error back:

```
Java exception in 'NativeModules'

java.lang.IncompatibleClassChangeError: The method 'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)' was expected to be of type static but instead was found to be of type virtual (declaration of 'com.google.android.gms.iid.zzak' appears in /data/app/it.wammo.wammo-1/base.apk)
```

**Comment by zedtux** [comment] 2018-05-28 12:16
@vdumontier solution, based on @cihadturhan's comment, works fine for me 👍

**Comment by xSmoggeRx** [comment] 2018-05-28 14:10
@Richi2293  try to clean cache and reinstall npm

**Comment by Pollizzio** [comment] 2018-05-28 14:34
I fixed adding in my grade.properties:
googlePlayServicesVersion=10.0.1

**Comment by Richi2293** [comment] 2018-05-28 15:01
yes now no longer returns errors but the onesignal library stopped working, maybe it can stop working some functionality. Better control

**Comment by orzhtml** [comment] 2018-05-29 02:14
Modify the file: android/build.gradle
`
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.2'

//        classpath 'com.android.tools.build:gradle:3.0.0' // <- USE 2.2.+ version

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        // Add jitpack repository (added by react-native-spinkit)
        maven { url "https://jitpack.io" }
        mavenLocal()
        google()
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
//            url "https://maven.google.com"
        }

    }
}`
And this file：android/gradle/wrapper/gradle-wrapper.properties
`distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=http\://services.gradle.org/distributions/gradle-4.1-all.zip`

**Comment by booker0108** [comment] 2018-05-29 02:59
I wonder why this plugin need google play service

**Comment by machour** [comment] 2018-06-01 07:16
Seems like this temporary problem with jcenter() is now over. Closing this issue.

**Closed by machour** 2018-06-01 07:16 UTC

**Comment by fangcaiwen** [comment] 2018-07-04 08:56
感谢，如此奇葩，移动位置就可以

**Comment by VahidBo** [comment] 2018-07-06 05:35
I'm facing this issue again since I upgraded my `react-native` to version 0.56.0.

**Comment by machour** [comment] 2018-07-23 16:23
@VahidBo This is a totally different issue. Please open a new ticket.

**Comment by knockmark10** [comment] 2018-08-03 19:00
Same thing is happening to me. It hadn't happened anything like this before. I tried comments above and no luck. Everytime I rebuilt, different errors apperar. Help!

**Comment by gabriellacerda** [comment] 2018-10-23 15:08
@vitrum you did it!

**Comment by TomDoge** [comment] 2019-01-22 09:53
> I tried put google() before jcenter() and also use url 'https://maven.google.com' instead the previous url I had and nothing works for me. I hope this should be fixed.

just put google() before jcenter() , and it`s OK
