### ISSUE TITLE
React/RCTBridgeModule.h not found

### ISSUE THREAD

**Issue by dozel** [rebeccahughes/react-native-device-info#146] opened 2017-01-25 21:04 UTC
This error just popped out of the blue. Has anyone run into this issue?

**Comment by MattHall** [comment] 2017-01-25 21:55
I'm trying with a new generated app via ignite:

```
ignite --version
> 1.13.0
```

Error:
```
In file included from /Users/Matt/Work/ed/scratch/node_modules/react-native-device-info/RNDeviceInfo/RNDeviceInfo.m:9:
/Users/Matt/Work/ed/scratch/node_modules/react-native-device-info/RNDeviceInfo/RNDeviceInfo.h:12:9: fatal error: 'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>
        ^
1 error generated.
```

**Comment by dozel** [comment] 2017-01-25 23:04
The way I got around this error for now was keeping the version at 0.9.7. If you have a carrot in your package.json ( "^0.9.7"), just remove the carrot (^) and it should be fine for now. 

My RN project is using 0.34, so maybe that's the cause of this problem.

**Comment by MattHall** [comment] 2017-01-25 23:23
Hmm - possibly related to https://github.com/rebeccahughes/react-native-device-info/issues/140 then?

**Comment by MattHall** [comment] 2017-01-26 17:37
OK, so running `react-native upgrade` then `react-native upgrade` again (accepting all changes both times) and then `react-native run-ios` worked. It moved the app back to react-native 0.38.

**Comment by derekgreenberg** [comment] 2017-01-26 17:46
This issue was caused by an error in the semantic versioning, which was fixed about 20 hours ago. Now, when running 'npm i' or 'yarn' with "react-native-device-info": "^0.9.6" in your package.json, version 0.9.9 will be installed, which effectively restores the iOS native header to the version that was in 0.9.7.

**Comment by MattHall** [comment] 2017-01-26 17:55
Running `react-native link` causes the original error to reoccur, but even after building successfully, I see
```
undefined is not an object (evaluating 'RNDeviceInfo.systemManufacturer')
```

**Comment by MattHall** [comment] 2017-01-26 18:32
OK, so starting afresh worked perfectly. Thanks @derekgreenberg 👍

**Comment by derekgreenberg** [comment] 2017-01-26 18:42
@MattHall Sorry - should have mentioned that this fix is for those who are starting afresh, such as Ignite 1.13.0 users who are generating a new project.

**Comment by MattHall** [comment] 2017-01-26 18:46
Yep - sorry. Forgot this wasn't my issue!

**Comment by ThisIsMissEm** [comment] 2017-03-07 22:46
If you version is 0.10.0, then this is no longer compatible with RN < 0.40, see #140 for detailed conversation (it is actually possible to support both RN < 0.40.0 and RN >= 0.40.0, it's just more work

**Comment by Laconty** [comment] 2017-05-19 09:16
Product -> Schemes -> Manage schemes... -> (your project) -> tab build -> (uncheck checkbox "Parallelize Build")

**Comment by paulbrittain** [comment] 2017-11-15 14:03
@Laconty there is no build tab anymore.

**Closed** 2018-02-03 10:59 UTC
Labels: ios

**Comment by jeremyfrancis** [comment] 2018-04-19 17:38
Just had to react-native run-ios instead of trying to run from Xcode. That put everything together right I guess.
