### ISSUE TITLE
Can all the manual setup be avoided with rnpm?

### ISSUE THREAD

**Issue by ahmed1490** [rebeccahughes/react-native-device-info#23] opened 2016-02-04 22:18 UTC
rnpm link > https://github.com/rnpm/rnpm

**Comment by grittathh** [comment] 2016-02-29 22:16
Yes, at least on ios rnpm link works.

**Comment by rebeccahughes** [comment] 2016-04-11 15:39
Duplicate of #29

**Closed by rebeccahughes** 2016-04-11 15:39 UTC
