### ISSUE TITLE
Error: more than one library with package name 'com.google.android.gms.license'

### ISSUE THREAD

**Issue by manju-ms** [rebeccahughes/react-native-device-info#379] opened 2018-03-29 06:11 UTC
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.17.3   |
| Affected OS | Android  |

## Current behavior

When compiling My react-native project i am getting the above error. 

In my app/build.gradle file have excluded the Play servies version as shown below.

compile (project(':react-native-device-info')) {
       exclude(group: 'com.google.android.gms', module: 'play-services-gcm')
}

Even though i have excluded the play-services-gcm, Y i am getting this Error?

**Comment by machour** [comment] 2018-03-29 07:48
Duplicate of #366

**Closed by machour** 2018-03-29 07:48 UTC

**Comment by manju-ms** [comment] 2018-04-04 14:09
@machour, thank you for your response. The app is working fine. Can i know even though excluding the 'play-services-gcm' in build.gradle, why i am getting more than one library issue?. My concern is, if i force the app to use 11.8.0 version other plugins may required 12.0 version and this may lead to crash of app again. Correct if i am wrong.
