### ISSUE TITLE
Unable to merge dex

### ISSUE THREAD

**Issue by kylesziv** [rebeccahughes/react-native-device-info#299] opened 2018-01-27 18:25 UTC
I get this error when I add this plugin to my project:

```
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
```

**Comment by machour** [comment] 2018-01-30 10:40
Hi @kylesziv, could you provide the complete error log? Usually there are more bits prior and after this message that would help pinpointing your problem

**Comment by vijaychouhan-rails** [comment] 2018-01-30 13:58
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

**Comment by machour** [comment] 2018-01-30 14:01
And the lines before that? How are you building your app?

**Comment by vijaychouhan-rails** [comment] 2018-01-30 14:04
react-native run-android 
Scanning folders for symlinks in /node_modules (7ms)
Building and installing the app on the device (cd android && ./gradlew installDebug)...

> Configure project :app
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 9.0.0 will be used.
please apply google-services plugin at the bottom of the build file.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)

> Configure project :react-native-device-info
Configuration 'compile' in project ':react-native-device-info' is deprecated. Use 'implementation' instead.
WARNING: The specified Android SDK Build Tools version (25.0.2) is ignored, as it is below the minimum supported version (26.0.2) for Android Gradle Plugin 3.0.1.
Android SDK Build Tools 26.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:processDebugGoogleServices
Parsing json file: /home/rails/work/vijay/ChatMeApp/android/app/google-services.json


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
36 actionable tasks: 2 executed, 34 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by vijaychouhan-rails** [comment] 2018-01-30 14:05
"react": "16.2.0",
 "react-native": "0.52.2",

**Comment by vijaychouhan-rails** [comment] 2018-01-30 14:26
@machour , any thoughts how to solve this?

**Comment by machour** [comment] 2018-01-30 14:27
I'm wondering if the problem could be with Google Play services, which is
mentioned before the error and which is required by this lib..

**Comment by machour** [comment] 2018-01-30 14:30
Run this command to get a complete stacktrace:

cd android && ./gradlew installDebug --stacktrace

**Comment by vijaychouhan-rails** [comment] 2018-01-30 14:44
@machour 

> Configure project :app
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
google-services plugin could not detect any version for com.google.android.gms or com.google.firebase, default version: 9.0.0 will be used.
please apply google-services plugin at the bottom of the build file.
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)

> Configure project :react-native-device-info
Configuration 'compile' in project ':react-native-device-info' is deprecated. Use 'implementation' instead.
WARNING: The specified Android SDK Build Tools version (25.0.2) is ignored, as it is below the minimum supported version (26.0.2) for Android Gradle Plugin 3.0.1.
Android SDK Build Tools 26.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '25.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:processDebugGoogleServices
Parsing json file: /home/rails/work/vijay/ChatMeApp/android/app/google-services.json


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
        at com.android.builder.dexing.DxDexArchiveMerger.mergeMultidex(DxDexArchiveMerger.java:266)
        at com.android.builder.dexing.DxDexArchiveMerger.mergeDexArchives(DxDexArchiveMerger.java:133)
        at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:97)
        at com.android.build.gradle.internal.transforms.ExternalLibsMergerTransform.transform(ExternalLibsMergerTransform.kt:121)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:222)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:218)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:213)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 27 more
Caused by: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
Caused by: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
        at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:72)
        at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Caused by: com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/FirebaseException;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
        at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
        ... 1 more


* Get more help at https://help.gradle.org

BUILD FAILED in 7s
42 actionable tasks: 39 executed, 3 up-to-date

**Comment by machour** [comment] 2018-01-30 15:05
There you go, this is the relevant error message:

```
Caused by: com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/FirebaseException;
```

I think that your import is conflicting with the one from this library.  Check this SO answer to see how to exclude the one from this lib: https://stackoverflow.com/a/46988337/732772

**Comment by vijaychouhan-rails** [comment] 2018-01-30 15:19
@machour ,

Thanks, its works.
Solution is:
```

dependencies {
  compile 'com.google.firebase:firebase-core:11.8.0' //Added this line
}

```

**Comment by machour** [comment] 2018-01-30 15:23
Awesome, thank you for reporting back!

**Comment by kylesziv** [comment] 2018-02-01 00:46
Where do I put the above solution?

**Comment by machour** [comment] 2018-02-01 08:45
@vijaychouhan-rails could you give more information to @kylesziv and then close this issue?

**Comment by vijaychouhan-rails** [comment] 2018-02-01 08:52
@machour @kylesziv 

I added this line at `<PROJECT LOCATION>/android/app/build.gradle`

**Comment by paintedbicycle** [comment] 2018-02-19 15:13
I got this error too, when using RNFirebase. When I removed Google Play services manually from react-native-device-info and used it in my own project, the issue went away. It's definitely to do with google-play-services and will likely affect any project using two packages that both need it. Not sure how integral play services are to RNDeviceInfo, but would be great to remove that dependency.

**Comment by machour** [comment] 2018-02-23 16:06
This is now mentioned in the [troubleshooting section](https://github.com/rebeccahughes/react-native-device-info#troubleshooting) of the README file.

@paintedbicycle I'm planning to drop the dependency in 1.0.0 (#307), can't do it prior to a BC breaking release

**Closed by machour** 2018-02-23 16:06 UTC
Labels: :book: docs, :robot: android

**Comment by zurez** [comment] 2018-02-28 13:45
Current version is v0.17.2 . When do you plan to release the 1.0.0.
Your library is amazing and firebase is amazing too, and I want to keep both.
So thank you very much for your efforts.

**Comment by machour** [comment] 2018-02-28 13:51
@zurez thank you for reaching out.
I'm currently waiting to merge or close the remaining PRs and setup a Windows 10 computer to be able to work on the react-native-windows binding, I'd hate to lose windows compatibility for 1.0

**Comment by welkensoyo** [comment] 2018-03-25 20:13
You can easily resolve incompatibilities now by adding 
`cordova.system.library.7=com.android.support:appcompat-v7:27.1.0`
to your project.properties

**Comment by shafqatsiddiqui** [comment] 2018-12-17 07:54
delete the build folder in android build folder build it again

**Comment by NomanGul** [comment] 2019-04-22 07:36
Just run gradlew clean :smiley: 

`cd android && ./gradlew clean`

**Comment by AndlerRL** [comment] 2020-07-02 22:56
> Just run gradlew clean 😃
> 
> `cd android && ./gradlew clean`


Nice! Maybe the issue can relate to prev app versions and package changes that maybe did a conflict. Doing the clean did the work for me!

**Comment by tomsiwik** [comment] 2020-07-24 22:10
@vijaychouhan-rails solution kind of worked, except I had to add the line, build and delete it again. Otherwise it would crash on start. Aber that everything seemed to work again. Strange.

**Comment by mikehardy** [comment] 2020-07-24 23:04
No one should have to do anything like that for an android build ever. Something is very wrong with any project that requires that.

**Comment by mikehardy** [comment] 2020-07-24 23:05
`npx react-native-clean-project` perhaps.

**Comment by ettingshausen** [comment] 2020-11-17 05:51
Add `multiDexEnabled true`
```groovy
defaultConfig {
        applicationId "com.xxx"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
```
Works for me!
