### ISSUE TITLE
Crash userAgent

### ISSUE THREAD

**Issue by iclems** [rebeccahughes/react-native-device-info#161] opened 2017-03-17 18:50 UTC
Getting random crashes when the app is in background here: 
RNDeviceInfo.m line 134 -[RNDeviceInfo userAgent]

**Comment by Ouadie** [comment] 2017-05-05 10:08
same here

**Comment by samarchyan** [comment] 2017-05-12 17:55
+1

**Comment by machour** [comment] 2018-02-14 14:45
Duplicate of #89

**Closed by machour** 2018-02-14 14:45 UTC
