### ISSUE TITLE
Is it support react-native 0.40?

### ISSUE THREAD

**Issue by musicode** [rebeccahughes/react-native-device-info#140] opened 2017-01-13 10:47 UTC

**Comment by Hyllesen** [comment] 2017-01-13 10:57
Have you tried? What error are you getting if it doesn't work?

**Comment by jhillnz** [comment] 2017-01-16 05:02
Headers are namespaced with react-native 0.40.0 https://github.com/facebook/react-native/wiki/Breaking-Changes#040

Small change required here https://github.com/rebeccahughes/react-native-device-info/blob/master/RNDeviceInfo/RNDeviceInfo.h#L12

**Comment by jhillnz** [comment] 2017-01-17 01:43
Your package.json is 0.9.6 but npmjs badge reports latest as 0.9.7. The later includes header fix required for react-native 0.40.0.

**Comment by freiserg** [comment] 2017-01-24 09:52
@GantMan Could you release new version of plugin for support RN 0.40?

**Comment by ThisIsMissEm** [comment] 2017-01-24 22:22
@jhillnz interestingly, npm shows a version who's code appears not to be on github: it shows a 0.9.7, but latest on gothub is 0.9.6; @GantMan in details on getting these two synced up?

(We're going to need RN v0.40 support soon, and will have to fork if a new release doesn't come out)

**Comment by ThisIsMissEm** [comment] 2017-01-24 22:23
If the issue is in supporting both versions of RN, see: https://medium.com/@thisismissem/how-to-upgrade-react-native-modules-in-a-backwards-compatible-manner-a5b5c48d590c#.is7osygsb

**Comment by alfonsodev** [comment] 2017-01-25 18:27
I can confirm that the npm package version is different.  
It doesn't contain [this header change](https://github.com/rebeccahughes/react-native-device-info/commit/5834bf6c4c48d26b555cf90abb0a6e5537a54f06#diff-769c725b34aa1f00cce03fa63e7960d1R12)  
Although I also have to confirm that even though the header is not changed, the module works on react-native 0.40, anyone can explain how's that possible ?  

btw, @ThisIsMissEm thanks for the article is great value, I'm using that macro for my pull request to other modules.  
https://github.com/marcshilling/react-native-idle-timer/pull/6/files  
https://github.com/stefalda/ReactNativeLocalization/pull/58/files

**Comment by GantMan** [comment] 2017-01-25 19:29
Sorry all, -  I'll release this now
Been a busy week.  We're doing the all-team retreat for Infinite Red, and little work is being done, hah.

**Comment by devbriguy** [comment] 2017-03-07 17:34
I think this issue can be closed as PR Update iOS RN header paths #121 address this. Thanks!

**Comment by ThisIsMissEm** [comment] 2017-03-07 22:44
@GantMan @rebeccahughes @devbriguy — yes, this can be closed, however, the current release is not compatible with RN < 0.40.0 (see: https://medium.com/@thisismissem/how-to-upgrade-react-native-modules-in-a-backwards-compatible-manner-a5b5c48d590c )

**Closed** 2017-03-07 23:08 UTC
