### ISSUE TITLE
uses or overrides a deprecated API. Recompile with -Xlint:deprecation for details.

### ISSUE THREAD

**Issue by mrkhanakia** [rebeccahughes/react-native-device-info#472] opened 2018-08-09 06:12 UTC
I am getting error during Gradle build

/Volumes/D/www/js/uc_js/uc_reactnative/node_modules/react-native-device-info/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details.

**Comment by machour** [comment] 2018-08-09 08:14
Duplicate of #325

**Closed by machour** 2018-08-09 08:14 UTC
